# Generated by Django 5.0.3 on 2024-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_agentprofile_customerprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='transaction_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
